server:
  port: 8081

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/unjobs
    username: unjobs
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    elasicsearch:
#      cluster-name: 704477490845:unjobs
#      cluster-nodes: https://search-unjobs-whenkya5bzpav7tif3ejrzvk5y.us-east-1.es.amazonaws.com
#      username: admin
#      password: Moa@8055



